name: Build Dependencies
inputs:
  mobilePath:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install React Native CLI
      shell: bash
      run: |
        yarn global add react-native-cli

    - name: Install client packages
      working-directory: ${{ inputs.mobilePath }}
      shell: bash
      run: |
        yarn --frozen-lockfile
