name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Download Android Emulator Image
        run: |        
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
          echo "Yes" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Pixel_API_31_AOSP --device "pixel" -k 'system-images;android-29;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Client dependencies
        uses: ./.github/workflows/dependencies
        with:
          mobilePath: ./

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r21e

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Install dependencies
        run: yarn

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Android Detox
        run: detox build -c android.emu.release

      - name: Download Android Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install $PACKAGE
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name Pixel_API_31_AOSP --device "pixel_5" --package $PACKAGE --sdcard 256M
          # adb start-server
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list device
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd
        env:
          PACKAGE: 'system-images;android-29;default;x86_64'

      - name: Change Android Emulator settings
        run: |
          echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
          mkdir -p /root/.android && touch /root/.android/repositories.cfg
          echo "vm.heapSize=576" >> $AVD_PATH/config.ini
          echo "hw.ramSize=2048" >> $AVD_PATH/config.ini
          echo "disk.dataPartition.size=2048m" >> $AVD_PATH/config.ini
          grep "size" $AVD_PATH/config.ini
        env:
          AVD_NAME: Pixel_API_31_AOSP
          AVD_PATH: /Users/runner/.android/avd/Pixel_API_31_AOSP.avd

      - name: Install node_modules
        run: |
          npm install
      - name: Android Emulator
        timeout-minutes: 10
        continue-on-error: true
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -verbose -no-audio -no-snapshot -no-window -gpu swiftshader_indirect @Pixel_API_31_AOSP &
          # nohup $ANDROID_HOME/emulator/emulator -verbose -no-audio -no-snapshot -no-window -partition-size 2048 @Pixel_API_31_AOSP &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
          echo "Emulator started"

      - name: Android Detox
        run: yarn start & detox test -c android.emu.release

      - name: Store Detox artifacts on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: detox-artifacts
          path: artifacts # Default path for Detox artifacts
