name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    - name: Client dependencies
      uses: ./.github/workflows/dependencies
      with:
        mobilePath: ./client
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r21e
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
